routes/web.php
<?php

use App\User;
use App\Ticket_IT;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StaffVerifyController;
use Spatie\Permission\Middlewares\RoleMiddleware;
use Spatie\Permission\Middlewares\PermissionMiddleware;
use Spatie\Permission\Middlewares\RoleOrPermissionMiddleware;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/register_staff', function () {
    return view('auth.register_staff');
})->name('registerStaff');

Route::post('/register_staff_email', 'Auth\RegisterController@registerEmail')->name('registerEmail');

Route::get('/verify_staff/{id}', 'Auth\VerificationController@verifyStaff')->name('verifyStaff');

Route::post('/verifying_staff/{id}', 'Auth\VerificationController@verifyingStaff')->name('verifyingStaff');

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('urf_control','URFController')->middleware('auth');
Route::resource('staff_tracking','StaffTrackingController')->middleware('auth');
Route::resource('staff_draft','StaffDraftController')->middleware('auth');
Route::resource('staff_verify','StaffVerifyController')->middleware('auth');
Route::resource('staff_approve','StaffApproveController')->middleware('auth');
Route::resource('ict_verify','ICTVerifyController')->middleware('auth');
Route::resource('ict_approve','ICTApproveController')->middleware('auth');
Route::resource('ict_assign','ICTAssignController')->middleware('auth');
Route::resource('ict_pic','ICTPicController')->middleware('auth');
Route::resource('maintain_param','MaintainParamController')->middleware('auth');
Route::resource('maintain_urf','MaintainURFController')->middleware('auth');
Route::resource('secure_profile','SecureProfileController')->middleware('auth');
Route::resource('secure_email','SecureEmailController')->middleware('auth');
Route::resource('secure_site','SecureSiteController')->middleware('auth');
Route::resource('secure_usersetting','SecureUserSettingController')->middleware('auth');
Route::resource('report_master','ReportMasterController')->middleware('auth');

Route::get('/ticket/{id}', function($id) {
    $ticket = Ticket_IT::find($id);
    // dd(Auth::user()->roles->first()->name);
    if($ticket->urf_status == "stat01"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOU', 'HOU', 'Super Admin'))){
            return redirect()->route('staff_verify.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

    if($ticket->urf_status == "stat02"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOD', 'HOD', 'Super Admin'))){
            return redirect()->route('staff_approve.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

    if($ticket->urf_status == "stat04"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOU', 'HOU', 'Super Admin'))){
            return redirect()->route('ict_verify.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

    if($ticket->urf_status == "stat17"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOD', 'Super Admin'))){
            return redirect()->route('ict_approve.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

    if($ticket->urf_status == "stat18"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOD', 'HOD', 'Super Admin'))){
            return redirect()->route('staff_approve.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

    if($ticket->urf_status == "stat19"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOU', 'Super Admin'))){
            return redirect()->route('ict_verify.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

    if($ticket->urf_status == "stat22"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOD', 'HOD', 'Super Admin'))){
            return redirect()->route('staff_approve.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

})->name('ticket');
// Route::resource('report','ReportController');

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\Facades\DataTables;

class ReportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/ReportMasterController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Ticket_IT;
use Carbon\Carbon;
use App\Ticket_IT_Log;
use Illuminate\Http\Request;
use App\Exports\TicketExport;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Support\Facades\App;
use Maatwebsite\Excel\Facades\Excel;
use Yajra\DataTables\Facades\DataTables;


class ReportMasterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = Ticket_IT::with(['users', 'req_users', 'departments', 'req_departments', 'request_types', 'requirement_types', 'applications', 'criticalities','status'])
            ->distinct()
            ->first();

        if ($request->ajax()) {
            // $data = Student::latest()->get();
            $data = Ticket_IT::with(['users', 'req_users', 'departments', 'req_departments', 'request_types', 'requirement_types', 'applications', 'criticalities','status'])
            ->distinct()
            ->get();

            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('urf_no', function($row){
                    // if( in_array($row->urf_status, array('stat01', 'stat02', 'stat03', 'stat05', 'stat08', 'stat13')) )
                    // {
                        return "URF".sprintf('%05d', $row->id);
                    // }else
                    //     return "ETS".sprintf('%05d', $row->urf_no);
                })
                ->addColumn('fullname', function($row){
                    return $row->users->fullname;
                })
                ->addColumn('mergeColumn', function($row){
                    if($row->request_type == "rq01" || $row->request_type == "Application"){
                        return $row->request_types->param_desc." - ".$row->applications->param_desc;
                    }
                    else{
                        return $row->request_types->param_desc;
                    }
                })
                ->addColumn('urf_status', function($row){
                    if($row->urf_status == "stat12"){
                        if($row->assignTo == "ass01"){
                            return $row->status->param_desc." - Assigned to ".$row->officers->fullname;
                        }else{
                            return $row->status->param_desc." - Assigned to Vendor";
                        }
                    }else{
                        return $row->status->param_desc;
                    }
                })
                ->addColumn('action', function($row){
                    $actionBtn = '<a href="'.route('report_master.show', $row->id).'"><button class="btn btn-primary btn-sm downloadPDF"><i class="mdi mdi-file-pdf"></i></button></a></td>';
                    return $actionBtn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }

        return view('report.report_master.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Download Master Report
        if($request->has('masterReport')){
            return Excel::download(new TicketExport, 'ticket.xlsx');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tracking = Ticket_IT::with([
            'users',
            'req_users',
            'departments',
            'req_departments',
            'request_types',
            'requirement_types',
            'applications',
            'criticalities',
            'status',
            'assignees',
            'officers',
            'complexities',
            'requirement_types_it',
            'owners',
        ])->where('id', $id)->first();
        // dd($tracking);
        $log = Ticket_IT_Log::with('status', 'tickets')
        ->where('urf_no', '=', $id)
        ->distinct()
        ->get();
            // dd($log);

        // foreach($log as $log){
        //     dd($log);
        // }
        $pdf = PDF::loadView('report.pdf', compact('tracking', 'log'))->setOptions(['defaultFont' => 'sans-serif']);
        // dd($pdf);

        // return $pdf->stream('tracking.pdf');
        // dd($pdf);
        $fileName =  time().'.'. 'pdf' ;
        $pdf->save($fileName);

        $pdf = public_path($fileName);
        return response()->download($pdf);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        // $tracking = Ticket_IT::where('id', $id)->with([
        //     'users',
        //     'req_users',
        //     'departments',
        //     'req_departments',
        //     'request_types',
        //     'requirement_types',
        //     'applications',
        //     'criticalities',
        //     'status',
        //     'assignees',
        //     'officers',
        //     'complexities',
        //     'requirement_types_it',
        //     'owners',
        // ])->distinct()->first();

        // $users = User::query()
        // ->when($request->requestor_fullname, function($query, $requestor_id){
        //     return $query->where('id', $requestor_id);
        // });

        // if ($request->ajax() && $request->requestor_fullname) {
        //     $department = $users->first()->departments->param_desc;
        //     $users = $users->first();
        //     return ['department' => $department, 'users' => $users];
        // }

        // $users = $users->get();


        // return view('report.report_master.edit', compact('tracking', 'users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

resources/views/report/report_master/index.blade.php
@extends('layouts.app_layout')

@section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <div class="p-2">
                            <h3 class="card-title">Master Report</h3>
                        </div>
                        <div class="p-2">
                            <form action="{{ route('report_master.store') }}" method="POST">@csrf
                                <button type="submit" class="btn btn-primary btn-sm" name="masterReport">Excel</button>
                            </form>
                        </div>
                    </div>
                    <p class="card-description">
                    <!-- Add class <code>.table-bordered</code> -->
                    </p>
                    <div class="table-responsive pt-3">
                        <table class="table table-bordered table-striped yajra-datatable">
                            <thead>
                                <tr>
                                    <th>

                                    </th>
                                    <th>
                                    URF No.
                                    </th>
                                    <th>
                                    Full Name
                                    </th>
                                    <th>
                                    Request Type
                                    </th>
                                    <th>
                                    Status
                                    </th>
                                    <th>

                                    </th>
                                </tr>
                            </thead>

                            <tbody>

                            </tbody>
                            </form>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')
<script type="text/javascript">
    $(".downloadPDF").click(function(){
    var data = '';
    $.ajax({
        type: 'GET',
        url: "{{ route('report_master.show', $data->id) }}",
        data: data,
        xhrFields: {
            responseType: 'blob'
        },
        success: function(response){
            var blob = new Blob([response]);
            var link = document.createElement('a');
            link.href = window.URL.createObjectURL(blob);
            link.download = "Sample.pdf";
            link.click();
        },
        error: function(blob){
            console.log(blob);
        }
    });
    });
  $(function () {
    var table = $('.yajra-datatable').DataTable({
    processing: true,
    serverSide: true,
    ajax: "{{ route('report_master.index') }}",
    columns: [
      {data: 'DT_RowIndex', name: 'DT_RowIndex'},
      {data: 'urf_no', name: 'urf_no'},
      {data: 'fullname', name: 'fullname'},
      {data: 'mergeColumn', name: 'mergeColumn'},
      {data: 'urf_status', name: 'urf_status'},
      {data: 'action', name: 'action', orderable: true, searchable: true},
    ]});
  });

</script>
@endpush