routes/web.php
<?php

use App\User;
use App\Ticket_IT;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StaffVerifyController;
use Spatie\Permission\Middlewares\RoleMiddleware;
use Spatie\Permission\Middlewares\PermissionMiddleware;
use Spatie\Permission\Middlewares\RoleOrPermissionMiddleware;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/register_staff', function () {
    return view('auth.register_staff');
})->name('registerStaff');

Route::post('/register_staff_email', 'Auth\RegisterController@registerEmail')->name('registerEmail');

Route::get('/verify_staff/{id}', 'Auth\VerificationController@verifyStaff')->name('verifyStaff');

Route::post('/verifying_staff/{id}', 'Auth\VerificationController@verifyingStaff')->name('verifyingStaff');

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('urf_control','URFController')->middleware('auth');
Route::resource('staff_tracking','StaffTrackingController')->middleware('auth');
Route::resource('staff_draft','StaffDraftController')->middleware('auth');
Route::resource('staff_verify','StaffVerifyController')->middleware('auth');
Route::resource('staff_approve','StaffApproveController')->middleware('auth');
Route::resource('ict_verify','ICTVerifyController')->middleware('auth');
Route::resource('ict_approve','ICTApproveController')->middleware('auth');
Route::resource('ict_assign','ICTAssignController')->middleware('auth');
Route::resource('ict_pic','ICTPicController')->middleware('auth');
Route::resource('maintain_param','MaintainParamController')->middleware('auth');
Route::resource('maintain_urf','MaintainURFController')->middleware('auth');
Route::resource('secure_profile','SecureProfileController')->middleware('auth');
Route::resource('secure_email','SecureEmailController')->middleware('auth');
Route::resource('secure_site','SecureSiteController')->middleware('auth');
Route::resource('secure_usersetting','SecureUserSettingController')->middleware('auth');
Route::resource('report_master','ReportMasterController')->middleware('auth');

Route::get('/ticket/{id}', function($id) {
    $ticket = Ticket_IT::find($id);
    // dd(Auth::user()->roles->first()->name);
    if($ticket->urf_status == "stat01"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOU', 'HOU', 'Super Admin'))){
            return redirect()->route('staff_verify.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

    if($ticket->urf_status == "stat02"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOD', 'HOD', 'Super Admin'))){
            return redirect()->route('staff_approve.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

    if($ticket->urf_status == "stat04"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOU', 'HOU', 'Super Admin'))){
            return redirect()->route('ict_verify.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

    if($ticket->urf_status == "stat17"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOD', 'Super Admin'))){
            return redirect()->route('ict_approve.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

    if($ticket->urf_status == "stat18"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOD', 'HOD', 'Super Admin'))){
            return redirect()->route('staff_approve.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

    if($ticket->urf_status == "stat19"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOU', 'Super Admin'))){
            return redirect()->route('ict_verify.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

    if($ticket->urf_status == "stat22"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOD', 'HOD', 'Super Admin'))){
            return redirect()->route('staff_approve.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

})->name('ticket');
// Route::resource('report','ReportController');

app/Http/Controllers/SecureUserSettingController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\UserLog;
use App\Parameter;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Auth;
use Intervention\Image\Facades\Image;
use Yajra\DataTables\Facades\DataTables;

class SecureUserSettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            // $data = Student::latest()->get();
            $data = User::distinct()->with(['departments', 'units', 'branches', 'user_status', 'roles_param'])->orderBy('fullname')->get();

            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('status', function($row){
                    return $row->user_status->param_desc;
                })
                ->addColumn('action', function($row){
                    // $actionBtn = '<a href="javascript:void(0)" class="edit btn btn-success btn-sm">Edit</a> <a href="javascript:void(0)" class="delete btn btn-danger btn-sm">Delete</a>';
                    $actionBtn = '<a href="'. route('secure_usersetting.edit', $row->id ) .'"><button class="btn btn-primary btn-sm"><i class="mdi mdi-magnify"></i></button></button></a></td>';
                    return $actionBtn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }

        return view('security.secure_usersetting.index');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $users = User::with(['departments', 'units', 'branches', 'user_status', 'roles_param', 'roles'])
        ->distinct()
        ->where('id', $id)->first();
        // dd($users);

        $unit = $this->getParameter('unit');
        $branch = $this->getParameter('branch');
        $department = $this->getParameter('department');
        $roles = $this->getRole();


        return view('security.secure_usersetting.edit', compact('users', 'unit', 'branch', 'department', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if($request->has('changerole'))
        {
            UserLog::create([
                'user_id' => Auth::id(),
                'attempt' => 'att08',
                'user_created' => Auth::user()->fullname,
                'user_lastmaintain' => Auth::user()->fullname,
            ]);

            $user = User::find($id);
            $user->syncRoles($request->role_id);
        }

        if($request->has('changepass')){
            $validatepass = $request->validate([
                'password' => 'required|min:8|confirmed',
            ]);

            UserLog::create([
                'user_id' => Auth::id(),
                'attempt' => 'att05',
                'user_created' => Auth::user()->fullname,
                'user_lastmaintain' => Auth::user()->fullname,
            ]);

            $changepassword = User::where('id', $id)->update(['password' => bcrypt($request->password)]);
        }

        if($request->has('changeava')){
            if($request->file('avatar_path')){
                $fileName = Carbon::now()->format('Y-m-d').'_'.$request->file('avatar_path')->getClientOriginalName();
                $filePath = $request->file('avatar_path')->storeAs('storage/avatars', $fileName, 'public');
                $img = Image::make($request->file('avatar_path')->getRealPath());
                $img->resizeCanvas(1500, 1500, 'center');
                // $img->greyscale();
                $img->save(public_path('images/faces/'.$fileName));
                // dd($img);
            }

            UserLog::create([
                'user_id' => Auth::id(),
                'attempt' => 'att01',
                'user_created' => Auth::user()->fullname,
                'user_lastmaintain' => Auth::user()->fullname,
            ]);

            User::where('id', $id)->update([
                'avatar_name' => $fileName,
                'avatar_path' => $filePath
            ]);
        }

        if($request->has('changedept')){
            UserLog::create([
                'user_id' => Auth::id(),
                'attempt' => 'att02',
                'user_created' => Auth::user()->fullname,
                'user_lastmaintain' => Auth::user()->fullname,
            ]);

            User::where('id', $id)->update([
                'department' => $request->department,
            ]);
        }

        if($request->has('changeunit')){
            UserLog::create([
                'user_id' => Auth::id(),
                'attempt' => 'att03',
                'user_created' => Auth::user()->fullname,
                'user_lastmaintain' => Auth::user()->fullname,
            ]);

            User::where('id', $id)->update([
                'unit' => $request->unit,
            ]);
        }

        if($request->has('changebranch')){
            UserLog::create([
                'user_id' => Auth::id(),
                'attempt' => 'att04',
                'user_created' => Auth::user()->fullname,
                'user_lastmaintain' => Auth::user()->fullname,
            ]);

            User::where('id', $id)->update([
                'branch' => $request->branch,
            ]);
        }

        return redirect()->route('secure_usersetting.index')->with('msg', 'success');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function getParameter($parameter_name){
        return Parameter::select('param_code', 'param_desc')
        ->where('category_code', $parameter_name)
        ->orderBy('param_desc')
        ->pluck('param_desc', 'param_code');
    }

    public function getRole(){
        return Role::select('id', 'name')
        ->orderBy('id')
        ->pluck('name', 'id');
    }
}

resources/views/security/secure_usersetting/edit.blade.php
@extends('layouts.app_layout')

@section('content')

<div class="content-wrapper">
    <div class="row">
        <div class="col-12 grid-margin">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <div class="p-2">
                            <h4 class="card-title">{{$users->fullname}}'s Profile</h4>
                            <p class="card-description">{{$users->fullname}}'s Details</p>
                        </div>
                        <div class="p-2">
                            <form method="POST" action="{{ route('secure_usersetting.update', $users->id) }}" enctype="multipart/form-data">
                                <img class="img-xs rounded-circle"
                                @if(!$users->avatar_name) src="{{ asset('images/faces/default.png') }}"
                                @else src="{{ asset('images/faces/'.$users->avatar_name) }}"
                                @endif alt="Profile image" >
                                    @method('put')
                                    @csrf
                                <a class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target=".changeavatar">Change Avatar</a>
                                @include('modal/secure_changeavatar/changeavatar')
                            </form>
                        </div>
                    </div>
                    <div class="form-sample">
                        <div class="row text-center">
                            {{-- <div class="col-md-6">
                                <div class="form-group">
                                    <label>Username</label>
                                    <div class="align-self-center" >
                                    <input type="text" class="form-control" value="{{$users->username}}" disabled/>
                                    </div>
                                </div>
                            </div> --}}
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Full Name</label>
                                    <div class="align-self-center">
                                    <input type="text" class="form-control text-center" value="{{$users->fullname}}" disabled/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>E-Mail Address</label>
                                    <div class="align-self-center">
                                    <input type="email" class="form-control text-center" value="{{$users->email}}" disabled/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <form method="POST" action="{{ route('secure_usersetting.update', $users->id) }}" >
                                    @method('put')
                                    @csrf
                                    <div class="form-group">
                                        <label>Password</label>
                                        <div class="align-self-center">
                                        <a class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target=".changepassword">Change Password</a>
                                        </div>
                                        @include('modal/secure_changepassword/changepassword')
                                        @error('password')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </form>
                            </div>
                            <form method="POST" action="{{ route('secure_usersetting.update', $users->id) }}" >
                                @method('put')
                                @csrf
                                <div class="col-md">
                                    <label>User's Role:</label>
                                    @foreach($roles as $id => $value)
                                    <label class="form-check-label mx-2">
                                        <input class="checkbox" type="checkbox" name="role_id[]" value="{{$id}}" @foreach ($users->roles()->select('id')->pluck('id') as $role_id) {{ $role_id == $id ? 'checked' : ''}} @endforeach>
                                        {{$value}}
                                    </label>
                                    @endforeach
                                </div>
                                <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-2">
                                    <button type="submit" class="btn btn-primary btn-sm" name="changerole">Save Changes</button>
                                </div>
                            </form>
                        </div>
                        <hr>
                        <div class="row">
                            <form method="POST" action="{{ route('secure_usersetting.update', $users->id) }}">
                                @method('put')
                                @csrf
                                <div class="col-md">
                                    <div class="form-group">
                                        <label>Department/Sect</label>
                                        <select class="form-control" name="department" id="department">
                                            <option value="{{$users->department}}" selected>{{$users->departments->param_desc}} - Selected</option>
                                            @foreach($department as $id => $value)
                                            <option value="{{$id}}">{{$value}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                    <button type="submit" class="btn btn-primary btn-sm" name="changedept">Save Changes</button>
                                </div>
                            </form>
                            <form method="POST" action="{{ route('secure_usersetting.update', $users->id) }}">
                                @method('put')
                                @csrf
                                <div class="col-md">
                                    <div class="form-group">
                                        <label>Unit</label>
                                        <select class="form-control" name="unit" id="unit">
                                            <option value="{{$users->unit}}" selected>{{$users->units->param_desc}} - Selected</option>
                                            @foreach($unit as $id => $value)
                                            <option value="{{$id}}">{{$value}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                    <button type="submit" class="btn btn-primary btn-sm" name="changeunit">Save Changes</button>
                                </div>
                            </form>
                            <form method="POST" action="{{ route('secure_usersetting.update', $users->id) }}">
                                @method('put')
                                @csrf
                                <div class="col-md">
                                    <div class="form-group">
                                        <label>Branch</label>
                                        <select class="form-control" name="branch" id="branch">
                                            <option value="{{$users->branch}}" selected>{{$users->branches->param_desc}} - Selected</option>
                                            @foreach($branch as $id => $value)
                                            <option value="{{$id}}">{{$value}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                    <button type="submit" class="btn btn-primary btn-sm" name="changebranch">Save Changes</button>
                                </div>
                            </form>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label>Status </label>
                                </div>
                            </div>
                            <div class="col-md-10">
                                <div class="form-group">
                                    <input type="text" class="p-1 form-control-plaintext" value="{{$users->user_status->param_desc}}" disabled/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@include('modal/secure_changepassword/notsame')

@endsection

@push('js')

<script>
    var myModal = new bootstrap.Modal(document.querySelector('.notsame'), {});

    $(document).ready(function(){
        @if(session('msg'))
            $('.notsame .modal-body').html('<span class="text-success">Password changed successfully.</span>');
            myModal.show();
        @endif

        @if($errors->any())
            $('.notsame .modal-body').html('<span class="text-danger">Failed to change password. Check error message.</span>');
            myModal.show();
        @endif
    });
</script>

@endpush

resources/views/security/secure_usersetting/index.blade.php
@extends('layouts.app_layout')

@section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">User Setting</h4>
                    <p class="card-description">
                    <!-- Add class <code>.table-bordered</code> -->
                    </p>
                    <div class="table-responsive pt-3">
                        <table class="table table-bordered table-striped yajra-datatable">
                            <thead>
                            <tr>
                                <th>

                                </th>
                                <th>
                                Username
                                </th>
                                <th>
                                Full Name
                                </th>
                                <th>
                                E-Mail
                                </th>
                                <th>
                                Ext. Phone No.
                                </th>
                                <th>
                                Status
                                </th>
                                <th>

                                </th>
                            </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@include('modal/secure_changepassword/notsame')

@push('js')
<script type="text/javascript">
  $(function () {
    var table = $('.yajra-datatable').DataTable({
    processing: true,
    serverSide: true,
    ajax: "{{ route('secure_usersetting.index') }}",
    columns: [
      {data: 'DT_RowIndex', name: 'DT_RowIndex'},
      {data: 'username', name: 'username'},
      {data: 'fullname', name: 'fullname'},
      {data: 'email', name: 'email'},
      {data: 'ext_phone_no', name: 'ext_phone_no'},
      {data: 'status', name: 'status'},
      {data: 'action', name: 'action', orderable: true, searchable: true},
    ]});
  });

  var myModal = new bootstrap.Modal(document.querySelector('.notsame'), {});
  $(document).ready(function(){
        @if(session('msg'))
            $('.notsame .modal-body').html('<span class="text-success">Changes has made successfully.</span>');
            myModal.show();
        @endif

        @if($errors->any())
            $('.notsame .modal-body').html('<span class="text-danger">Failed to make changes. Check error message.</span>');
            myModal.show();
        @endif
    });
</script>
@endpush