routes/web.php
<?php

use App\User;
use App\Ticket_IT;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StaffVerifyController;
use Spatie\Permission\Middlewares\RoleMiddleware;
use Spatie\Permission\Middlewares\PermissionMiddleware;
use Spatie\Permission\Middlewares\RoleOrPermissionMiddleware;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/register_staff', function () {
    return view('auth.register_staff');
})->name('registerStaff');

Route::post('/register_staff_email', 'Auth\RegisterController@registerEmail')->name('registerEmail');

Route::get('/verify_staff/{id}', 'Auth\VerificationController@verifyStaff')->name('verifyStaff');

Route::post('/verifying_staff/{id}', 'Auth\VerificationController@verifyingStaff')->name('verifyingStaff');

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('urf_control','URFController')->middleware('auth');
Route::resource('staff_tracking','StaffTrackingController')->middleware('auth');
Route::resource('staff_draft','StaffDraftController')->middleware('auth');
Route::resource('staff_verify','StaffVerifyController')->middleware('auth');
Route::resource('staff_approve','StaffApproveController')->middleware('auth');
Route::resource('ict_verify','ICTVerifyController')->middleware('auth');
Route::resource('ict_approve','ICTApproveController')->middleware('auth');
Route::resource('ict_assign','ICTAssignController')->middleware('auth');
Route::resource('ict_pic','ICTPicController')->middleware('auth');
Route::resource('maintain_param','MaintainParamController')->middleware('auth');
Route::resource('maintain_urf','MaintainURFController')->middleware('auth');
Route::resource('secure_profile','SecureProfileController')->middleware('auth');
Route::resource('secure_email','SecureEmailController')->middleware('auth');
Route::resource('secure_site','SecureSiteController')->middleware('auth');
Route::resource('secure_usersetting','SecureUserSettingController')->middleware('auth');
Route::resource('report_master','ReportMasterController')->middleware('auth');

Route::get('/ticket/{id}', function($id) {
    $ticket = Ticket_IT::find($id);
    // dd(Auth::user()->roles->first()->name);
    if($ticket->urf_status == "stat01"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOU', 'HOU', 'Super Admin'))){
            return redirect()->route('staff_verify.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

    if($ticket->urf_status == "stat02"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOD', 'HOD', 'Super Admin'))){
            return redirect()->route('staff_approve.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

    if($ticket->urf_status == "stat04"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOU', 'HOU', 'Super Admin'))){
            return redirect()->route('ict_verify.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

    if($ticket->urf_status == "stat17"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOD', 'Super Admin'))){
            return redirect()->route('ict_approve.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

    if($ticket->urf_status == "stat18"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOD', 'HOD', 'Super Admin'))){
            return redirect()->route('staff_approve.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

    if($ticket->urf_status == "stat19"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOU', 'Super Admin'))){
            return redirect()->route('ict_verify.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

    if($ticket->urf_status == "stat22"){
        if(in_array(Auth::user()->roles->first()->name, array('ICT HOD', 'HOD', 'Super Admin'))){
            return redirect()->route('staff_approve.edit', $ticket->id);
        }else{
            return redirect()->route('staff_tracking.edit', $ticket->id);
        }
    }

})->name('ticket');
// Route::resource('report','ReportController');

resources/views/modal/maintain/param/delete.blade.php
<div class="modal fade delete" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="{{ route('maintain_param.destroy', $parameters->id) }}" >
                @method('delete')
                @csrf
                <div class="modal-body">
                    <label>Are you sure you want to proceed?</label>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-success" type="submit" name="deleteparam">Yes</button>
                    <button type="button" class="btn btn-danger close" data-bs-dismiss="modal" aria-label="Close">No</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/modal/maintain/param/save.blade.php
<div class="modal fade save" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Save Changes</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <label>Are you sure you want to proceed?</label>
            </div>
            <div class="modal-footer">
                <button class="btn btn-success" type="submit">Yes</button>
                <button type="button" class="btn btn-danger close" data-bs-dismiss="modal" aria-label="Close">Cancel</button>
            </div>
        </div>
    </div>
</div>